import Head from 'next/head'
import Navegation from './portafolio/components/navegation'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main >
      <Navegation></Navegation>
      </main>

    </>
  )
}
